### ISSUE TITLE
Connection Lost: Disconnected upon joining singleplayer world

### ISSUE THREAD

**Issue by jakeee51** [hammy3502/mc-vr-api#22]
```java
public class PlayerInitHandler {
    @SubscribeEvent
    public void onPlayerLogin(PlayerEvent.PlayerLoggedInEvent event) {
        System.out.println("HANDLE PLAYER LOGIN EVENT");
        LocalPlayer player = getMCI().player;
        assert player != null;
        System.out.println("PLAYER NOT NULL");
        VrJesterApi.VIVECRAFTLOADED = PositionTracker.vrAPI.playerInVR(player);
        System.out.println("CRASHES BEFORE THIS");
    }
}
```
I register the above handler in the `MinecraftForge.EVENT_BUS` and it causes the player to disconnect from joining their singleplayer world. I'm trying to assign a flag so I can check throughout my code whether the player is in VR or not. Please find attached gifs and snippet of logs for visual reference.

https://gyazo.com/c2abe794e0a5d21abee8faf94c5a8e22
https://gyazo.com/8674f8a3d827bb3505da4fcb159569d5
![image](https://user-images.githubusercontent.com/19763930/200714688-c63a558c-57cb-4552-9b82-e7c3fc602ce8.png)

-Thanks

**Comment by hammy275** [comment]
Assuming `getMCI()` is the same as `Minecraft.getInstance()`, I don't think the `ClientPlayer` object exists that early to be grabbed. `playerInVR` is a pretty light function that you can keep using instead of the field.

I might add a function that initializes much earlier to check if a player is in VR client-side, but if you absolutely need it as a field, _I think_ you can call any of the `getVRPlayer()` methods that don't take a player, and check if they're `null` or not (such as `getPreTickVRPlayer()`). 

Or if that doesn't work, you can register an EventListener for one of the player tick events specifically from the method that receives your `IVRAPI` instance, and set your field to `true` there after it makes the check you're making now (when the `ClientPlayer` is certain to exist), with it defaulting to `false` otherwise. That way, it only gets set to `true` if you get an `IVRAPI` instance AND you're in VR.

**Comment by jakeee51** [comment]
Ya, that sounds good to me! I was able to successfully work around it. Just wanted to bring it to your attention. Gonna go ahead and close the issue.

-Thanks
